# Generated by Django 2.1.7 on 2019-03-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("groups", "0002_auto_20190322_1825")]

    operations = [
        migrations.AlterModelOptions(
            name="group", options={"ordering": ["-members__User"]}
        )
    ]
