# Generated by Django 2.1.7 on 2019-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190331_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Group name'),
        ),
    ]
